spring.application.name=LensLogic
spring.datasource.url=jdbc:postgresql://localhost:5432/vision_db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Max size for a single file
spring.servlet.multipart.max-file-size=100MB

# Max size for the entire request (files + other form data)
spring.servlet.multipart.max-request-size=100MB